### ISSUE TITLE
Snarl 5.0 Beta 7 Released!

### ISSUE THREAD

**Issue by fullphat** [fullphat/snarl#51]

**Comment by fullphat** [comment]
Beta 7 is [now available for download](https://sourceforge.net/projects/snarlwin/files/Snarl/R5/)!

Key changes:

- Can now specify a file path to sysadmin configuration.  To do this, use `path=xxx` in `redirect.rc`.  `url` takes priority over `path`, but if the file specified by `url` can't be loaded the file specified by `path` will be used instead.  (47.113)
- Must now specify the _full_ URL to the json configuration file when using `redirect.rc` to point to a URL.  (47.113)
- Now display 'n/a' in the app page if we can't resolve the registering computer's hostname.  (47.113)
- Fixed `App.IsRemote` and `App.RemoteComputerIP` to make them work again.  The information is now pulled from the app's configuration file (`most_recent_registration_from` property).  `App.IsRemote` simply returns `True` if this isn't `localhost` or null.  (47.113)

**Comment by fruza** [comment]
Hi!.

Still cannot place all configuration files: %APPDATA%\full phat\snarl 5.0\etc in a centralized server. Allways I run snarl, it's going to find the files to %APPDATA% :

> bootstrap: starting notification roster...
> NotificationRoster.Start(): %appdata% is C:\Users\ffrr12\AppData\Roaming\full phat\snarl 5.0\etc\
> NotificationRoster.Start(): loading osd.rc...
> NotificationRoster.readOsdConfig(): reading osd settings...
> NotificationRoster.Start(): checking osd presets folder...
> NotificationRoster.getOsdPresets(): loading osd presets...
> bootstrap: starting application roster...
> reading from: C:\Users\ffrr12\AppData\Roaming\full phat\snarl 5.0\etc\registrations.rc
> reading from: C:\Users\ffrr12\AppData\Roaming\full phat\snarl 5.0\etc\apps\15ec1f44-9a5b-42b9-afa4-459a0163330f.rc
> reading from: C:\Users\ffrr12\AppData\Roaming\full phat\snarl 5.0\etc\apps\1a20183f-0b93-4744-8432-719491e96a95.rc
> Registering Snarl as an app...
> RulesRoster.Process(): not running!

I've trying **redirect.rc** but this file is to say where **sysadmin.json** is, not the .rc snarl configuration files.

Regards, Fernando.

**Comment by fullphat** [comment]
That’s right.  At the moment redirecting all of the local settings content isn’t in place just yet.  What are you looking to do?

**Comment by fruza** [comment]
I'm planning to deploy snarl to a thousand computers aproximately and I would like to have all of them with the same configuration. I would like to have all of the local settings content centralized in a file server so that it depends for computers not for user.

In olders versions I think it was possible to set this up with the file: **sysconfig.ssl** as it's detailed here: [https://sites.google.com/site/snarlapp/help-and-support/snarl-administration-guide](url)

Best regards, Fernando.

**Comment by fullphat** [comment]
Understood!  I had a think about this and I’ve decided to rework the way Snarl manages its settings.  This has been on the roadmap for some time, but it’s now been bumped up the list.  :)

Currently, settings are mainly held in “ini” style files, which, while easy to manage, are quite restrictive.  

I’ve now made a start on flattening all these files into a single “settings.json” file.  The key benefit here (other than the ability to easily parse and use classes to determine the contents) is that we’ve now moved from tens of separate files to one single file, which can easily be redirected.

To this end, I’ve also added two new settings to the sysadmin JSON file - ConfigFileUrl and ConfigFilePath - which can now point to the full Snarl settings file to use.  If either of these are used, Snarl will assume the settings are read-only too.

This all probably sounds quite complicated :) so I will make sure the sysadmin guide is updated in time for the next beta release.

One last feature to mention is that you can now make Snarl reload its settings dynamically by calling Oxide `/diagnostics/reload_settings` which could be useful if you modify your global settings file and need all your Snarl instances to reload the modified file.

**Comment by fullphat** [comment]
Very soon 😀 I'm just making some final changes and then I'll get it posted.  In the meantime, I've updated the SysAdmin guide a bit so you can see what's coming: https://github.com/fullphat/snarl/wiki/SysAdmin-Guide
